baseurl: "https://vriphys2019.github.io/"
title: "The 15th Workshop on Virtual Reality Interaction and Physical Simulation (VRIPHYS'19)"
canonifyurls: true
theme: "hugo-conference"

#GoogleAnalytics: "UA-9232216-1"

params:
  # Conference info
  Name: "VRIPHYS'19"
  Description: "The 15th Workshop on Virtual Reality Interaction and Physical Simulation"
  Date: "May 5, 2019"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Porto Antico Conference Center"
  Address: Magazzini del Cotone, 16128 Genova GE
  City:  "Genoa"
  Country: "Italy"
  Logo: "/img/logo_color.png"
  Tagline: "The 15th Workshop on Virtual Reality Interaction and Physical Simulation"

  #GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    #- location
    #- cfp
    #- speakers
    #- organization
    #- schedule
    #- sponsors
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Keynote"
    organization: "Organization"
    cfp: "Call for Papers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register"
    link: "https://events.eg.org/crema/"

  # List of Sponsors
  #Sponsors:
  #  - name: "Hugo"
  #    logo: "/img/hugo.png"
  #    url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Eurographics"
      logo: "/img/EG_image.png"
      url: "https://www.eg.org/"

  # The entire schedule
  Schedule:
    - name: "Chris Wojtan"
      photo: "/img/chris_wojtan.png"
      bio: "Chris Wojtan received his B.S. in Computer Science in 2004 from the University of Illinois in Urbana Champaign and his Ph.D. in Computer Graphics from the Georgia Institute of Technology in 2010. He is a recipient of the National Science Foundation Graduate Research Fellowship, the Georgia Tech Sigma Xi Best Ph.D. Thesis Award, an ERC Starting Grant, the 2015 Eurographics Young Researcher Award, and the 2016 SIGGRAPH Significant New Researcher Award. Chris is currently a Professor at the Institute of Science and Technology Austria (IST Austria), and his current research interests are physically-based animation and geometry processing, with a recent emphasis on the simulation of fracture, turbulent fluids, and water surface waves."
      company: "IST Austria"
      link:
        href: "http://pub.ist.ac.at/group_wojtan/"
    #  presentation:
    #    title: "Digging into a Linux Kernel"
    #    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #    time: "10h00"
